### ISSUE TITLE
Question: Docker container?

### ISSUE THREAD

**Issue by stepman0** [Thyraz/Sonos-Kids-Controller#13]
Hi, I just found your project - i have to same situation (kids want to play music but I want to create a selection). Thanks a lot for your work - I will try it out the next days.

What just came to my mind? Have you considered creating a Docker container, this would/could make installation easier?

If not, I could give it a try and provide it...

Regards,

**Comment by stepman0** [comment]
I just found that there is a docker image available for node-sonos-http-api, it can be found at https://github.com/chrisns/docker-node-sonos-http-api. 

I forked this repo and referenced to your fork of node-sonos-http-api: https://github.com/stepman0/docker-node-sonos-http-api

Once I get CI fixed, docker images for node-sonos-http-api should be availble at:  https://hub.docker.com/repository/docker/stepman0/docker-node-sonos-http-api

Btw: I have setup the Sonos-Kids-Controller today an a Raspi - great!!! I plan to run the server side on my NAS (Synology), therefore Docker is necessary.

**Comment by murmeltier08** [comment]
I working in the moment to create a dockerfile
https://github.com/murmeltier08/Sonos-Kids-Controller
But this still in progress.

**Comment by murmeltier08** [comment]
https://hub.docker.com/repository/docker/murmeltier08/sonos-kids-controller

**Comment by murmeltier08** [comment]
I have now the first working image for arm und x64 in Docker Hub

**Comment by Thyraz** [comment]
Sadly I have never used docker (my home server is running Proxmox with LXC containers and VMs).
So I can't comment much on this topic.

I just wanted to suggest to post it over at the discussions,
as I can't help on this topic and therefore would close this issue.

But I see you already did that. ;)

**Comment by stepman0** [comment]
@murmeltier08 Thanks for your work. I have a few suggestions (sorry didn't have time earlier) - but we can discuss this in your repo.

**Comment by murmeltier08** [comment]
Thank you! I see your clean Dockerfile. You are welcome. I want to improve my Dockerfile. See us in the other repo!
