### ISSUE TITLE
No issues - but is it possible to use deezer or amazon Musik on the Sonos-Kids-Controlle?

### ISSUE THREAD

**Issue by NoTrace-Kai** [Thyraz/Sonos-Kids-Controller#2]
Hi there ...
bevor i buy all the things for the great Controller, i want to ask you if i can use deezer or amazon Musik with the controller?
Can i use the MP3 files from my nas easier?
Thanks Kai

**Comment by Thyraz** [comment]
Hi Kai,

node-sonos-http-api support deezer and amazon music, but my User Interface doesn't so far.
I also have the request to add Apple Music, maybe I can add all of them together.

But I'm currently busy with another project, so it might take a month or two...

About adding local files:
Sadly there isn't a better search for services other than Spotify.
This also applies to adding cover art.

All music services use node-sonos-http-api for searching and accessing files.
Only for Spotify I wrote a seperate search and artwork fetcher, as it provides a nice public API to fetch this information.

**Comment by NoTrace-Kai** [comment]
Hi ...

ok, thanks a lot for you information, than i will wait till you get time to update the new features ;)

CU Kai

**Comment by Thyraz** [comment]
Ok, I added Amazon Music and Apple Music.

For Deezer I'm afraid node-sonos-http-api is missing some needed endpoints.
I see only searching for stations by artist. 
So it looks like it can't be added, sorry.

**Comment by NoTrace-Kai** [comment]
Thanks a lot ... then i can try ;)
