### ISSUE TITLE
Looks like the connection to Spotify is not working

### ISSUE THREAD

**Issue by toO231** [Thyraz/Sonos-Kids-Controller#26]
For me, the installation worked almost smoothly, however, no albums are added actually.
Unfortunately, I do not get an error message. I can simply press Add. But nothing happens.

Strangely enough, no requests come to my created Spotify API either.

Does anyone have a hint ?

<img width="1673" alt="Bildschirmfoto 2021-01-23 um 16 11 55" src="https://user-images.githubusercontent.com/16475073/105605998-0a594700-5d97-11eb-8c38-4af3479c55e6.png">
<img width="1673" alt="Bildschirmfoto 2021-01-23 um 16 20 59" src="https://user-images.githubusercontent.com/16475073/105605994-09281a00-5d97-11eb-9176-47bb0c82db63.png">

**Comment by amueller-tech** [comment]
This happened to me when I forgot to add the correct spotify credentials to the config.json.
You can search for albums, but they won't be added.

**Comment by toO231** [comment]
> This happened to me when I forgot to add the correct spotify credentials to the config.json.
> You can search for albums, but they won't be added.

In config.json I entered my Spotify information. I think that looks right for now.
![Uploading 6EC0D345-9995-4D20-97C9-EDF1A721C6F4.jpeg…]()

**Comment by Thyraz** [comment]
Do you see any errors in the javascript console of the browser when you pressed the add button?

**Comment by NoTrace-Kai** [comment]
Hi ...

I also get this "error", when i want to add a cd from amazon, nothing happens after pressing the add-button.
Where can i find the "data.json" file on my raspberry?

CU Kai

**Comment by NoTrace-Kai** [comment]
Hi ...

in my case i edited the rights of the sonso-kids-controller and the node-sonos-http-api folder to chmod 777
and after that i could use the Webinterface ... perhaps i installed some things with "sudo" and that was not necessary ;)

CU Kai
