### ISSUE TITLE
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by NoTrace-Kai** [Thyraz/Sonos-Kids-Controller#3]
Hi.

Irgendwas mache ich doch falsch?! So ganz habe ich noch nicht verstanden in welcher Reihenfolge ich die verschiedenen Sachen installieren muss ... erst hatte ich diesen ERROR127 ... nun diesen hier:
"FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory"
Dieser taucht auf, wenn ich die beim Punkt: ionic build --prod bin.

So habe ich die Installation begonnen (mal ohne apt-get update/upgrade und auch mit) dann mit dem Dezemeber Image vo´n RasiOS und mit dem vom August ...

Erst habe ich die Einstellungen im Raspi-Config gemacht , dann NodeJS und NPM installiert, und anschließend mit dem Sonsos-Kids-Controller weiter ... und das ganze nun schon bestimmt 8 Mal ;(

Vielleicht hast Du ja nen Tip, wie ich das nun hinbekomme ... ?!

Danke und Gruß Kai

**Comment by KingKahn123** [comment]
Hi Kai,

den Fehler hatte ich glaube ich auch... Konnte ihn erst lösen als ich das ganze auf einem RPI4 mit mehr Arbeitsspeicher installiert habe. Bei einem RPI3b+ hat es bei mir nicht geklappt... Welche Hardware nutzt du?

Viele Grüße,
Kai

**Comment by NoTrace-Kai** [comment]
Hi Kai ;)

Ja, ich habe es auch mit dem dem RasPi3b+ versucht ... und auch schon mit dem RasPi4 (der hat aber auch nur 1GB RAM).
Ggf. könnte ich es noch mit einem anderen Pi4 versuchen (der hat mehr RAM), aber eigentlich wollte ich es gern auf dem 3er nutzen, den hatte ich noch "über".
In der Anleitung steht ja auch, das der 3er reichen sollte ... aber warum es nun nicht gehrt, verstehe ich nicht.
Oder mache ich an der Reihenfolge bei der Installation was falsch?

Danke und Gruß Kai

**Comment by KingKahn123** [comment]
Also bei mir ist der Fehler auch aufgetaucht bei "ionic build --prod bin". Ich hatte dann auch im Internet geschaut und versucht mit Befehlen mehr Speicher zuzuordnen. Das hat alles nicht geklappt. Bevor Du noch weiter probierst, würde ich es probehalber mal auf dem RPI4 probieren. Dann kannst Du ja alle übrigen Fehlermöglichkeiten ausschließen, wenn es klappt.

Ich hatte mir jetzt auch extra einen neuen Raspberry Pi 4 gekauft. Der steht bei mir unten im Keller und der Sonos Controller mit dem RPI3+ steht oben im Kinderzimmer und greift die Weboberfläche vom RPI4 zu. Auf dem RPI4 laufen auch noch andere kleinere Anwendungen. Von daher ist es nicht ganz so schlimm, dass ich extra nochmal einen gekauft habe.

Ich musste beim RPI4 eigentlich nur das Display drehen. Mehr habe ich nicht gemacht. Momentan nutze ich Spotify und Apple Music... Apple Music hat Thyraz ja vor kurzem hinzugefügt, da muss ich jetzt alles umziehen, was schon mit ein bißchen Aufwand verbunden ist, da die API von AppleMusic ja nicht so mächtig hinsichtlich der Suchfunktion ist.

**Comment by NoTrace-Kai** [comment]
OK, ich starte dann mal nen Test mit einem RPi4 mit 4GB RAM ... auf dem RPi4 mit 1GB RAM bin ich ja auf den selben Fehler gestossen.
Ggf. kann man die SD-Karte ja auch vom RPi4 in den RPi3 packen, wenn alles soweit installiert ist ;) ?!
Dann mache ich mich mal ans Werk, danke für die Infos ...

**Comment by Thyraz** [comment]
Hi zusammen,

bei mir läuft auf dem Pi nur das Webfrontent.
Der Rest auf dem SmartHome Server.
Chromium auf dem Pi lädt die Seite also einfach von einem anderen Host.

Kann wirklich sein, dass das Ionic Frontend zum kompilieren mehr RAM braucht.

Was ihr machen könnt: 
Das ionic build --prod kompliert ja nur aus dem Quellcode das www-Verzeichnis, welches danach vom node.js Server ausgeliefert wird.

Dieses www Verzeichnis ist praktisch die WebApp an sich die im Browser läuft.
Das Verzeichnis muss aber an sich nicht auf dem Rechner kompliiert werden auf dem das nachher laufen soll.

Sprich: holt euch das Repository nicht nur auf den Pi sondern auch auf euren Rechner.
Installiert dort Node damit ihr ein npm install und das ionic build --prod machen könnt.

Das generierte www Verzeichnis kopiert ihr dann auf den Pi an den richtigen Fleck.

**Comment by NoTrace-Kai** [comment]
Hallo ...

Das wäre auch ne Alternative ;) Aber ich habe es nun auf dem RPi4 gemacht und alles hat mit der Installation geklappt.
Aber wenn ich nun den RasPi starte kommt die Weboberfläche nicht ... ;(
Die beiden "Homepages" Pi:8200 und Pi:5005 kann ich am PC aufrufen, aber anscheinend startet der X-Server nicht.

Gruß Kai

**Comment by Thyraz** [comment]
Auf dem 4er läuft auch Raspbian Lite ohne mitgelieferten X-Server, so dass du wie in der Readme beschrieben Openbox installiert hast?
Oder hast du da was anderes eingesetzt?

Bootmessages siehst du aber, nur der X-Server startet nicht?
Und siehst du dann die Shell wo du Befehle eingeben kannst, oder wie ist der Endzustand.

Einen Pi 4 zum Testen habe ich leider nicht griffbereit, aber kann ja auch noch an was anderem liegen...

**Comment by NoTrace-Kai** [comment]
Hi ...
ich habe es nach Deiner Anleitung gemacht ... Die Lite Version und dann:

`Now we install Openbox as a lightweight window manager:
sudo apt-get install --no-install-recommends xserver-xorg x11-xserver-utils xinit openbox
And Chromium as a browser:
sudo apt-get install --no-install-recommends chromium-browser`

Kann auf dem 5" Display nicht erkennen wie die Fehlermeldung genau aussieht, das bekomme ich noch nicht auf die 800x480 skaliert ... warum auch immer ;(

Dann habe ich die /etc/xdg/openbox/autostart bearbeitet und die IP von meinem Pi eingetragen.

`# Disable screen saver / power management
xset s off
xset s noblank
xset -dpms

# Start Chromium
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
chromium-browser --disable-infobars --kiosk 'http://192.168.2.188:8200'`

und im root-Verzeichis eine .bash-profile angelegt.

**Comment by NoTrace-Kai** [comment]
![image](https://user-images.githubusercontent.com/34300928/101791037-60ce3700-3b03-11eb-9161-2dedff703049.jpeg)

**Comment by NoTrace-Kai** [comment]
Hab die SD nun mal im Pi3 versucht. 
Dort kann man den Fehler schon mal lesen. 

![image](https://user-images.githubusercontent.com/34300928/101807436-66cd1380-3b15-11eb-93d3-29b78c0aa064.jpeg)

**Comment by NoTrace-Kai** [comment]
Huhu ...

So, habe etwas getüftelt ... und nun geht die Bedienung über den Bowser vom PC schonmal ;)
Und der RasPi bootet nun auch in eine grafische Oberfläche ... aber er startet nicht die Homepage vom Player.
Wenn der RasPi bootet wird "LXDE10" gestartet und mehr passiert leider nicht.
Ich habe schon versucht den Kiosk Modus neu zu installieren, aber da wir mir nur gesagat das alles schon aktuell und drauf ist.

Danke für nen kleinen Tip ... CU Kai

**Comment by NoTrace-Kai** [comment]
Hab nochmal ein LogFile für Euch ... bekomme den Start der grafischen Oberfläche einfach nicht hin ;(

[    31.906] 
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
[    31.908] Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
[    31.909] Current Operating System: Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l
[    31.909] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 smsc95xx.macaddr=DC:A6:32:4A:0F:4B vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyS0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
[    31.914] Build Date: 01 December 2020  05:59:57PM
[    31.915] xorg-server 2:1.20.4-1+rpt2+deb10u2 (https://www.debian.org/support) 
[    31.915] Current version of pixman: 0.36.0
[    31.917] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    31.917] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    31.921] (==) Log file: "/home/pi/.local/share/xorg/Xorg.0.log", Time: Fri Dec 11 22:59:52 2020
[    31.944] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    31.946] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    31.959] (==) No Layout section.  Using the first Screen section.
[    31.959] (==) No screen section available. Using defaults.
[    31.959] (**) |-->Screen "Default Screen Section" (0)
[    31.959] (**) |   |-->Monitor "<default monitor>"
[    31.964] (==) No device specified for screen "Default Screen Section".
	Using the first device section listed.
[    31.964] (**) |   |-->Device "Allwinner A10/A13/A20 FBDEV"
[    31.964] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[    31.964] (==) Automatically adding devices
[    31.964] (==) Automatically enabling devices
[    31.964] (==) Automatically adding GPU devices
[    31.972] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    31.974] (WW) The directory "/usr/share/fonts/X11/misc" does not exist.
[    31.974] 	Entry deleted from font path.
[    31.974] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    31.974] 	Entry deleted from font path.
[    31.974] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    31.974] 	Entry deleted from font path.
[    31.974] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    31.974] 	Entry deleted from font path.
[    31.974] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    31.974] 	Entry deleted from font path.
[    31.974] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    31.974] 	Entry deleted from font path.
[    31.974] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    31.974] 	Entry deleted from font path.
[    31.974] (==) FontPath set to:
	built-ins
[    31.974] (==) ModulePath set to "/usr/lib/xorg/modules"
[    31.974] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    31.974] (II) Loader magic: 0x1fdf80
[    31.974] (II) Module ABI versions:
[    31.975] 	X.Org ANSI C Emulation: 0.4
[    31.975] 	X.Org Video Driver: 24.0
[    31.975] 	X.Org XInput driver : 24.1
[    31.975] 	X.Org Server Extension : 10.0
[    31.976] (++) using VT number 1

[    31.979] (II) systemd-logind: took control of session /org/freedesktop/login1/session/_31
[    31.981] (II) no primary bus or device found
[    31.981] (II) LoadModule: "glx"
[    31.986] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    32.064] (II) Module glx: vendor="X.Org Foundation"
[    32.064] 	compiled for 1.20.4, module version = 1.0.0
[    32.064] 	ABI class: X.Org Server Extension, version 10.0
[    32.064] (II) LoadModule: "fbturbo"
[    32.067] (WW) Warning, couldn't open module fbturbo
[    32.068] (EE) Failed to load module "fbturbo" (module does not exist, 0)
[    32.068] (EE) No drivers available.
[    32.068] (EE) 
Fatal server error:
[    32.068] (EE) no screens found(EE) 
[    32.068] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[    32.068] (EE) Please also check the log file at "/home/pi/.local/share/xorg/Xorg.0.log" for additional information.
[    32.068] (EE) 
[    32.071] (EE) Server terminated with error (1). Closing log file.

**Comment by NoTrace-Kai** [comment]
So ...

erst einmal vielen Dank für das coole Projekt und vielen Dank für die Hilfe(n) ... 
Ich habe nun einen anderen Weg gewählt und nun läuft der Controller auch.

Ich habe ein fertiges Image mit dem Kiosk-Mode gefunden:
https://github.com/futurice/chilipie-kiosk
und dann nach dieser Anleitung die Grundeinstellungen vorgenommen:
https://www.az-delivery.de/blogs/azdelivery-blog-fur-arduino-und-raspberry-pi/kiosk-modus-fuer-raspberry-pi

Danach habe ich dann "den Rest" aus der Sonos-Kids-Controller Anleitung ausgeführt ;)
Und siehe da es läuft nun ... ist zwar noch etwas aufwändig die einzelnen "CDs" von Amazon einzufügen,
aber das sollte ja machbar sein ...

Kann man die Liste eigentlich auch bearbeiten? Oder muss ich bei einer Falscheingabe die "CD" löschen und
neu anlegen?

Eine automatische Import-Funktion gibt es nicht, oder?
Das man quasi alle "Bibi und Tina"-Folgen oder "Bibi Blocksberg" "Importieren kann?

Nundenn ... erstmal nen schönen Abend und vielen Dank nochmal ...

Gruß Kai !

**Comment by Thyraz** [comment]
Bin leider auch nicht so erfahren mit grafischen Oberflächen unter Linux, laufen bei mir außer auf der Box auch nur headless als Server Systeme.

Was oben an der Fehlermeldung komisch ist:
Das steht was von LXDE.

Das sollte bei Raspbian Lite nicht installiert sein, da ja kein X mit kommt.
Wir installieren ja nur Openbox.
Irgendwas stimmt da nicht.

Die Liste kannst du auch händisch bearbeiten.

Siehe den letzten Teil von hier:
https://github.com/Thyraz/Sonos-Kids-Controller#apple-music-or-amazon-music-unlimited

Du kannst so die Inhalte auch einfügen indem du das JSON Gebilde entsprechend erweiterst, musst es nicht über die UI machen.

Automatischen Import ganzer Hörspielserien geht nur über Spotify.
Amazon bietet hier keine entsprechende API an.

Was man machen kann wenn man es mal erstellt hat:
Hier mit anderen solche Listen (fertig für C&P in die data.json) teilen, damit man gegenseitig von der Fleißarbeit profitiert:
https://github.com/Thyraz/Sonos-Kids-Controller/discussions

**Comment by Thyraz** [comment]
Original "out of memory" error fix is now described in the readme.
https://github.com/Thyraz/Sonos-Kids-Controller/commit/ed60ce6097d08d8c28b8f3fc4df68bfd9e2faece
