### ISSUE TITLE
Playback issues on startup

### ISSUE THREAD

**Issue by HeikoGr** [Thyraz/Sonos-Kids-Controller#46]
When using spotify on another client and starting Sonos-Kids-Controller the Box starts resuming the old track - not the selected.

**Comment by Thyraz** [comment]
Hi Heiko,

not sure if I completely understand the problem.
Do you e.g. start playback on the Sonos box (that is also used by your Kids-Controller) from your mobile phone, 
then try to start a new album from the Kids-Controller?

I also play a lot on my sons Sonos box from my mobile, but maybe it's a problem if the mobile phone didn't disconnect before the new playback.

**Comment by HeikoGr** [comment]
No. The problem occurs if i listen to Spotify on my smartphone. And then start listening to Spotify on the box. 

It will always continue the song listened on the smartphone and not the selected one. I have to leave the selected album (player) and return to the overview (medialist) and select tge album again.

By the way. I don't use sonos hardware. I have built an all in one box with running raspotify and glued two speakers inside. Maybe this causes the problem.

**Comment by HeikoGr** [comment]
ok. i think i found the reason in the spotifycontroller over here:
https://github.com/amueller-tech/spotifycontroller/blob/c820f5564b118585e8fb75709e668b66c6ba811f/spotify-control.js#L99
the play function throws an error and starts the function "handleSpotifyError" instead of starting to play.

i will open another ticket on the other repository and will try to solve the problem.

**Comment by Thyraz** [comment]
ok, thank you for the feedback. :)
