### ISSUE TITLE
TTS is not working

### ISSUE THREAD

**Issue by christoph-ng** [Thyraz/Sonos-Kids-Controller#49]
If've got a setup with two docker containers for sonos api and kids-controller.

TTS is working with the sonos-api for example: http://vm-docker.home.lan:5005/Buero/say/Hallo/de-de

It's enabled in the kids-controller config, but not working.

    "node-sonos-http-api": {
        "server": "xxx.xxx.xxx.xxx",
        "port": "5005",
        "rooms": [
            "Buero"
        ],
        "tts": {
            "enabled": true,
            "language": "de-de",
            "volume": "40"
        }
    },

**Comment by Thyraz** [comment]
Closing this as I haven't had time for this project over the last months and you most likely solved your problem or moved on with another solution. ;)

In case you still need help, tell me and I reopen the issue.
