### ISSUE TITLE
Can't add unique album ID (Spotify)

### ISSUE THREAD

**Issue by noestreich** [Thyraz/Sonos-Kids-Controller#5]
Great project and documentation. I had a straight-forward install. Thanks!

I have an issue populating the home-screen. All your example query strings are working fine (i.e. "artist:Max Kruse album:Urmel")

But i can't seem to add a specific album directly, using the unique album ID. I am not quite sure if i input the ID correctly. Let's take "[Lichterkinder - Weihnachts- und Winterlieder](https://open.spotify.com/album/0pKBO2kSYKw8WBCLkfHOJn?si=AYBAd8rCSiSCXHl87U_hcA)" fo example. The Album-ID would be **0pKBO2kSYKw8WBCLkfHOJn**, the URI **spotify:album:0pKBO2kSYKw8WBCLkfHOJn**. 

I tried to put in just the ID, the ID with the prefix "spotify:album:" but i only ever get so see "Eternal undefined" ;) 

i tried "id:0pKBO2kSYKw8WBCLkfHOJn" as a search-query with no luck whatsoever. 

Any ideas would be appriciated. 

<img width="494" alt="Bildschirmfoto 2020-12-21 um 23 26 01" src="https://user-images.githubusercontent.com/309419/102828044-062aba00-43e4-11eb-9d74-b39652141dd2.png">

<img width="507" alt="Bildschirmfoto 2020-12-21 um 23 26 22" src="https://user-images.githubusercontent.com/309419/102828054-088d1400-43e4-11eb-9b90-2c5e83c047d0.png">

**Comment by Thyraz** [comment]
Confirmed to be a bug.
Didn't use it myself so far.

Will fix it soon.

**Comment by imhofroger** [comment]
Hi all
i have fix it. Is on my fork. Cant make a pull request, have another open.
