### ISSUE TITLE
Box Size

### ISSUE THREAD

**Issue by murmeltier08** [Thyraz/Sonos-Kids-Controller#6]
I order the small box : " klein (0,5LIter | 12,7x9,7x4,2cm)" [Link](https://www.amazon.de/gp/product/B0841Q9CJ1/?th=1)
This one was to small. Perhaps it will be nice to add the Box size in the documentation? 
Is the "mittel (0,7Liter | 15,8x12x5,8cm)" the right one? 
Thank you for the nice project!

**Comment by Thyraz** [comment]
Hi murmeltier,

no I also used the small one.

As decribed in the Readme, I also had to use a cutter knive to remove some of the isolation ob the USB cable to fit it in the box.

Best regards,
Tobias

**Comment by murmeltier08** [comment]
I check it again. Perhaps we have in germany a smaller one. I add picture of the small one. 
![423E8586-FC64-430A-9EE0-604A2BF9BC44](https://user-images.githubusercontent.com/44034211/103155208-a9d9e880-479d-11eb-9692-461d63c7329a.jpeg)

**Comment by murmeltier08** [comment]
![Uploading 7F800373-13D2-4C01-AB76-4B2393EFEEF8.jpeg…]()

**Comment by murmeltier08** [comment]
![Uploading B4EE94CA-9B1B-41B9-A439-071B89CC07F5.jpeg…]()

**Comment by murmeltier08** [comment]
The other box fitts
![Uploading A0B68527-4E9E-4511-8B52-47685E69B23F.jpeg…]()

**Comment by Thyraz** [comment]
Ok, will measure again later at home. 

I also ordered from Amazon Germany.

**Comment by Thyraz** [comment]
It is really the mid size one, sorry.

I guess the problem is, that the black one with middle size is currently not available on Amazon Germany.
Therefore the link changes to the small one when you open it, instead the link to the size I originally copied.

I will add the size to the text in the Readme. 
Sorry that you bought the wrong box...

**Comment by murmeltier08** [comment]
Thank you! :-) Perhaps this help other people.
