### ISSUE TITLE
Local Audio playback in browser

### ISSUE THREAD

**Issue by ansgarschulte** [Thyraz/Sonos-Kids-Controller#7]
Hi 
is it possible to use it without sonos and do local playback in a browser?

**Comment by Thyraz** [comment]
Hi Ansgar,

this software is just a graphical remote for this node sonos http library: https://github.com/jishi/node-sonos-http-api/tree/master/lib/actions

So this isn't possible currently.

But the player controls are just a few http requests.
If you have a library to locally play music e.g. from Spotify that can be controlled through http requests,
you might be able to adjust this file for your needs:

https://github.com/Thyraz/Sonos-Kids-Controller/blob/master/src/app/player.service.ts

Regards,
Tobias
