### ISSUE TITLE
Solve: Only get 800x480 resolution 

### ISSUE THREAD

**Issue by murmeltier08** [Thyraz/Sonos-Kids-Controller#8]
I get only 640x480 instead of 800x480 resolution at Raspberry Pi 3.
Changing the /boot/config.txt not working, try different commands, the last one was: 
```
framebuffer_width=800
framebuffer_height=480
max_usb_current = 1
Hdmi_group = 2
Hdmi_mode = 87
Hdmi_cvt 800 480 60 6

```
 tvservice -s shows the wrong resolution 
`state 0xa [HDMI DMT (4) RGB full 4:3], 640x480 @ 60.00Hz, progressive`

I solve it with : 
https://elinux.org/R-Pi_Troubleshooting#Can_only_get_800x480_resolution_in_LXDE_.28Arch_linux.29

1. sudo nano /boot/cmdline.txt
2. insert this line
"dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext3 rootwait"

After reboot
fbset -s shows: 
```
mode "800x480"
    geometry 800 480 800 480 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode
```
Perhaps this will be a good hint for the documentation?

**Comment by Thyraz** [comment]
Hi murmeltier,

will take a closer look at my configuration if I inserted something similar and missed it in the Readme.
If it wasn't necessary for me, maybe a thread over at the discussions with solutions for the Display on various Pi versions might be a good idea. https://github.com/Thyraz/Sonos-Kids-Controller/discussions

That thread could be linked in the Readme.

**Comment by NoTrace-Kai** [comment]
Perhaps it works also with installing the drivers on the Raspberry Pi:
https://github.com/goodtft/LCD-show

**Comment by NoTrace-Kai** [comment]
I got it working with this insert in config.txt ... but I also had to rotate the LCD Screen 180° and the Touch-Settings also.
Now the Display is fitting in my Case ;)

hdmi_force_edid_audio=1
max_usb_current=1
hdmi_force_hotplug=1
config_hdmi_boost=7
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_drive=1
hdmi_cvt 800 480 60 6 0 0 0

CU Kai ...
